# Generated by Django 5.2.13 on 2026-04-22 21:11

from django.db import migrations


def consolidate_profiles(apps, schema_editor):
    """Profile becomes a singleton shared across both partners. Keep the
    profile with a due_date set (preferring the oldest), delete the rest."""
    Profile = apps.get_model("accounts", "Profile")

    keeper = (
        Profile.objects.filter(due_date__isnull=False).order_by("pk").first()
        or Profile.objects.order_by("pk").first()
    )
    if keeper is not None:
        Profile.objects.exclude(pk=keeper.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_partner'),
    ]

    operations = [
        migrations.RunPython(consolidate_profiles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
