# Generated by Django 5.2.13 on 2026-04-16 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KickCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveSmallIntegerField()),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kick_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True)),
                ('mood', models.CharField(choices=[('great', 'Great'), ('good', 'Good'), ('ok', 'OK'), ('bad', 'Bad'), ('terrible', 'Terrible')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-week_number'],
            },
        ),
    ]
