# Generated by Django 5.2.13 on 2026-04-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='mood',
            field=models.CharField(choices=[('great', 'Excelente'), ('good', 'Bien'), ('ok', 'Regular'), ('bad', 'Mal'), ('terrible', 'Muy mal')], max_length=10),
        ),
    ]
