# Generated by Django 5.2.13 on 2026-04-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('appointment_type', models.CharField(choices=[('obstetric', 'Obstetric'), ('ultrasound', 'Ultrasound'), ('lab', 'Lab Work'), ('nutrition', 'Nutrition'), ('other', 'Other')], max_length=20)),
                ('date', models.DateTimeField()),
                ('doctor', models.CharField(blank=True, max_length=200)),
                ('clinic', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
