# Generated by Django 5.2.13 on 2026-04-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('obstetric', 'Obstétrica'), ('ultrasound', 'Ecografía'), ('lab', 'Análisis'), ('nutrition', 'Nutrición'), ('other', 'Otro')], max_length=20),
        ),
    ]
