# Generated by Django 5.2.13 on 2026-04-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='google_calendar_event_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_event_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
