# Generated by Django 5.2.14 on 2026-07-14 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_pregnancyfile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancyfile',
            name='file',
            field=models.FileField(upload_to='pregnancy-files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf', 'mp4', 'mov', 'm4v', 'webm'])]),
        ),
    ]
